site_name: locom
site_url: https://localcompose.github.io/locom
repo_url: https://github.com/localcompose/locom
theme:
  name: material
  features:
    - navigation.tabs
    - content.tabs.link  # enables clickable OS tabs
nav:
  - Home: index.md
  - Installation & Usage:
      - Install & Setup: install.md
      - CLI Reference: cli-reference.md
  - Versions:
      - v0.0.3-poc: versions/0.0.3-poc/index.md
